name: Check Visa

on:
  schedule:
    - cron: '0 12 * * *'
  push:
    branches:
      - main

jobs:
  check_visa:
    environment: VISA_STRING
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script
      id: run-script
      continue-on-error: true
      run: |
        set +e
        python check_visa.py
        echo "MVCR_RC=$?" >> $GITHUB_OUTPUT
      env:
        VISA_STRING: ${{ secrets.VISA_STRING }}

    - name: SUCCESS
      if: steps.run-script.outputs.MVCR_RC == '0'
      run: echo "SUCCESS, ${{ steps.run-script.outputs.MVCR_RC }}"

    - name: IN PROGRESS
      if: steps.run-script.outputs.MVCR_RC == '1'
      run: echo "IN PROGRESS, ${{ steps.run-script.outputs.MVCR_RC }}"

    - name: NOT FOUND
      if: steps.run-script.outputs.MVCR_RC == '2'
      run: echo "NOT FOUND, ${{ steps.run-script.outputs.MVCR_RC }}"

    - name: REJECTED
      if: steps.run-script.outputs.MVCR_RC == '3'
      run: echo "REJECTED, ${{ steps.run-script.outputs.MVCR_RC }}"