name: Check Visa

on:
  schedule:
    - cron: '0 12 * * *'
  push:
    branches:
      - main

jobs:
  check_visa:
    name: "🧾 CHECK"
    environment: VISA_STRING
    runs-on: ubuntu-latest
    outputs:
      MVCR_RC: ${{ steps.run-script.outputs.MVCR_RC }}
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script
      id: run-script
      continue-on-error: true
      run: |
        set +e
        python check_visa.py
        echo "MVCR_RC=$?" >> $GITHUB_OUTPUT
      env:
        VISA_STRING: ${{ secrets.VISA_STRING }}

  success:
    name: "🎉 SUCCESS"
    needs: check_visa
    runs-on: ubuntu-latest
    if: ${{ needs.check_visa.outputs.MVCR_RC == '0' }}
    steps:
    - name: SUCCESS
      run: echo "SUCCESS"

  in_progress:
    name: "⏳ IN PROGRESS"
    needs: check_visa
    runs-on: ubuntu-latest
    if: ${{ needs.check_visa.outputs.MVCR_RC == '1' }}
    steps:
    - name: IN PROGRESS
      run: echo "IN PROGRESS"

  not_found:
    name: "❌ NOT FOUND" 
    needs: check_visa
    runs-on: ubuntu-latest
    if: ${{ needs.check_visa.outputs.MVCR_RC == '2' }}
    steps:
    - name: NOT FOUND
      run: echo "NOT FOUND"

  rejected:
    name: "🚫 REJECTED"
    needs: check_visa
    runs-on: ubuntu-latest
    if: ${{ needs.check_visa.outputs.MVCR_RC == '3' }}
    steps:
    - name: REJECTED
      run: echo "REJECTED"